# fly.toml app configuration file generated for hacchaanweb on 2023-06-23T23:23:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hacchaanweb"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
 
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
